" Gui specific options
"``````````````````````
highlight Cursor gui=reverse guifg=NONE guibg=NONE " Cursor is same color as text

set guioptions+=c " Use console for dialogs
set guioptions+=d " Use dark variant if possible
set guioptions-=m " Hide menu bar
set guioptions-=T " Hide tool bar
set guifont=FiraCode\ Nerd\ Font\ weight=450\ 11 " Font
set guiligatures=!\"#$%&()*+-./:<=>?@[]^_{\|~

if &diff
    set columns=208 " Set default column width
else
    set columns=104 " Set default column width
endif
set lines=42 " Set default lines


