" Gui specific options
"``````````````````````
set guioptions+=c,d                    " Use console for dialogs, use dark variant if possible
set guifont=Fira\ Code\ weight=450\ 12 " Font

if &diff
    set columns=208 " Set default column width
else
    set columns=104 " Set default column width
endif
