set nocompatible " Set no compatible

" Plugins - Vim-plug
" ``````````````````
call plug#begin()
" |-- Auto Pairs --|
  Plug 'jiangmiao/auto-pairs'
  let g:AutoPairs = {'(':')', '[':']', '{':'}'}

" |-- Colorschemes --|
"  Plug 'mkarmona/materialbox' " Light, Light Diff
"  Plug 'jacoborus/tender.vim' " Dark Diff
"  Plug 'ayu-theme/ayu-vim'    " Dark
"  Plug 'nanotech/jellybeans.vim'    " Light
"  Plug 'rakr/vim-two-firewatch'     " Light
"  Plug 'NLKNguyen/papercolor-theme' " Light
  Plug 'notpratheek/vim-sol'         " Light

" |-- CSS Colors --|
  "Plug 'ap/vim-css-color'

" |-- Cursorword --|
  Plug 'itchyny/vim-cursorword'

" |-- Indentline --|
  Plug 'Yggdroot/indentLine'
  let g:indentLine_char = '│'

" |-- Lightline --|
  Plug 'itchyny/lightline.vim'
  let g:lightline = {
    \ 'colorscheme': 'default', 
  	\ 'component': {
  	\   'lineinfo': ' %3l:%-2v',
  	\ },
  	\ 'component_function': {
  	\   'readonly': 'LightlineReadonly',
  	\   'fugitive': 'LightlineFugitive'
  	\ },
  	\ 'separator': { 'left': '', 'right': '' },
  	\ 'subseparator': { 'left': '', 'right': '' }
  	\ }
  function! LightlineReadonly()
    return &readonly ? '' : ''
  endfunction

" |-- Rainbow Parentheses --|
  Plug 'kien/rainbow_parentheses.vim'
  let g:rbpt_loadcmd_toggle = 0
  let g:rbpt_max = 8
  au VimEnter * RainbowParenthesesToggle
  au Syntax * RainbowParenthesesLoadBraces
  au Syntax * RainbowParenthesesLoadRound
  au Syntax * RainbowParenthesesLoadSquare
  let g:rbpt_colorpairs = [
    \ ['Yellow',      '#F75C03'],
    \ ['Green',       '#B4E33D'],
    \ ['Magenta',     '#8338ec'],
    \ ['DarkYellow',  '#fca311'],
    \ ['DarkBlue',    '#3a86ff'],
    \ ['Cyan',        '#f15bb5'],
    \ ['DarkMagenta', '#0d3b66'],
    \ ['Brown',       '#bc4749'],
    \ ]

" |-- Syntax Highlight --|
  Plug 'octol/vim-cpp-enhanced-highlight', { 'for': ['c', 'cpp'] }
  let g:cpp_class_decl_highlight            = 1
  let g:cpp_class_scope_highlight           = 1
  let g:cpp_concepts_highlight              = 1
  let g:cpp_member_variable_highlight       = 1
  let g:cpp_no_function_highlight           = 0
  let g:cpp_posix_standard                  = 1

call plug#end()


"" |-- Git Blamer --|
"  "Plug 'zivyangll/git-blame.vim'
"  "nnoremap <Leader>s :<C-u>call gitblame#echo()<CR>
"
"" |-- Profile Vim Startup --|
"  "Plug 'hyiltiz/vim-plugins-profile'
"
"" |-- Vim Signify --|
"  Plug 'mhinz/vim-signify'
"  "let g:signify_line_highlight = 1
"  let g:signify_fold_context = [1, 3] " [foldlevel0, foldlevel1]
"  " Commands:
"  "   SignifyDiff: Opens a diff in new tab
"  "   SignifyFold: Opens folded unchanged lines
"
"" |-- Vim Startify --|
"  Plug 'mhinz/vim-startify'
"
"" |-- Wilder --|
"  if v:version > 800
"    Plug 'gelguy/wilder.nvim'
"  endif


"" Colorscheme
"" ```````````
"if strftime('%H') > 7 && strftime('%H') < 19
"   "Light
"colorscheme materialbox
"else
"  "Dark
"    if &diff
"        colorscheme tender
"    else
"        colorscheme ayu
"    endif
"endif
"
"" Wilder Config
"" `````````````
"if v:version > 800
"" |-- Wilder --|
"  call wilder#enable_cmdline_enter()
"  set wildcharm=<Tab>
"  cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
"  cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
"  call wilder#set_option('modes', ['/', '?', ':'])
"endif


" Variables
" `````````
let &titleold             = getcwd() " Set console title to path on vim exit
let c_space_errors        = 1        " Highlight trailing spaces
let c_curly_error         = 1        " Show curly braces error
let g:diff_translations   = 0        " Disables localisations and speeds up syntax highlighting in diff mode
let g:load_doxygen_syntax = 1        " Recognize doxygen comment style
let g:netrw_liststyle     = 3        " Set netrw style as tree


" Config Options
" ``````````````
set autoread                     " Auto reload changed file
set clipboard=unnamedplus        " Use + clipboard buffer
set nobackup                     " Do not create backup file
set noswapfile                   " Disable swap file
set path+=**                     " Look for all files in sub dirs
set path+=/usr/include/c++/9.2.1 " include c++ header files


" Editor Settings
" ```````````````
set autoindent   " New line inherit the indentation of previous lines
set backspace=2  " Set backspace to indent,eol,start
set breakindent  " Every wrapped line will continue visually indented
set cindent      " C-style indentation"
set cpoptions+=Z " When using w! while the 'readonly' option is set,don't reset 'readonly'
set expandtab    " Convert tabs to spaces
set history=1000 " Increase undo limit
set shiftwidth=4 " When shifting, indent using spaces
"set smartindent  " Do smart autoindenting when starting a new line
set tabstop=4    " Indent using spaces
set wrap         " Wrap text
syn enable                   " Syntax highlighting on, w/o overriding


" UI Options
" ``````````
colorscheme sol              " Set colorscheme 
highlight clear CursorLine   " No underline on text when cursorline is on
highlight clear CursorLineNR " No underline on line numbers when cursorline is on
set confirm                  " Raise dialog on quit if file has unsaved changes
"set colorcolumn=101          " Highlight text boundary for character length greater than 100
"set culopt=number,screenline " Highlight current line and line number of current window
set cursorline               " Highlight the line currently under cursor
set lazyredraw               " Don't redraw screen on macros, registers and other commands.
set diffopt+=vertical        " Open diff in vertical split
set encoding=utf-8           " Handles multibyte characters correctly
"set list                     " Show special characters
"set lcs=space:·,tab:\ \     " Show space as ·, tab as clear spaces
set laststatus=2             " Show status line on the bottom on multiple files
set mouse=a                  " Enable mouse support
set noshowmode               " Don't show INSERT/NOMRAL/VISUAL modes
set number                   " Enable line number
set ruler                    " Show cursor position all time
set showcmd                  " Display incomplete command
set splitbelow               " Place new window below on :split
set splitright               " Place new window right on :vsplit
set termguicolors            " Enable true colors support
set t_Co=256                 " Set color size
set title                    " Set console title
set ttyfast                  " Smooth rendering
set ttymouse=sgr             " Fix mouse support in half screen
set visualbell               " Flash the screen instead of beeping on errors
set wildmenu                 " Show matching text on status line when <TAB>

" Auto Completion Settings
" ````````````````````````
"set complete+=d,t " scan for defined name/macro, include tag completion
"set cscopetag     " Use cscope for tag commands.
"set cscopeverbose " Give messages when adding a cscope database.
"set tagcase=smart " If search has uppercase then case sensitive search


" Search Options
" ``````````````
set hlsearch   " Enable search highlighting
set ignorecase " Ignore case when searching
set incsearch  " Incremental search that shows partial matches
set smartcase  " Switch search to case-sensitive when query contains an uppercase letter
set tags=~/tags


" Filetype Specific Options
" `````````````````````````
"autocmd BufNewFile,BufRead *.cyt set syntax=sh " Set cyt filetype as bash
"autocmd Filetype make set noexpandtab shiftwidth=4 softtabstop=0 nocin
"filetype plugin indent on   " File based indentation
