; Copyright © Microsoft Corp.

[Theme]
; Windows - IDS_THEME_DISPLAYNAME_AERO_LIGHT
DisplayName=dark
ThemeId={8C285613-8EF2-4DE0-8B14-19DEFEE30DD8}

; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=%SystemRoot%\System32\imageres.dll,-54
Empty=%SystemRoot%\System32\imageres.dll,-55

[Control Panel\Cursors]
AppStarting=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\busy_eoa.cur
Arrow=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\arrow_eoa.cur
Crosshair=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\cross_eoa.cur
Hand=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\link_eoa.cur
Help=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\helpsel_eoa.cur
IBeam=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\ibeam_eoa.cur
No=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\unavail_eoa.cur
NWPen=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\pen_eoa.cur
SizeAll=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\move_eoa.cur
SizeNESW=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\nesw_eoa.cur
SizeNS=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\ns_eoa.cur
SizeNWSE=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\nwse_eoa.cur
SizeWE=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\ew_eoa.cur
UpArrow=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\up_eoa.cur
Wait=%USERPROFILE%\AppData\Local\Microsoft\Windows\Cursors\wait_eoa.cur
DefaultValue=Windows Inverted

[Control Panel\Desktop]
Wallpaper=%USERPROFILE%\OneDrive - Microsoft\Pictures\light\windows-11-light-3840x2160-10072.png
Pattern=
MultimonBackgrounds=0
PicturePosition=4
WindowsSpotlight=0

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=1
ColorizationColor=0X6A160B
SystemMode=Dark
AppMode=Dark
VisualStyleVersion=10

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS

[Sounds]
; IDS_SCHEME_DEFAULT
SchemeName=@mmres.dll,-800

[Slideshow]
ImagesRootPIDL=JGAFA8BAJmxJEINxRzcDXGELGa35eLJAxAAAAAAAjj1CFFBBQl2Y0VnclNHAAoHAJAABA8uvKiV1ENOW86lLAAAAVozAAAAABAAAAAAAaAGAQCEAAAAAAo9puEAUAkGAjBAdAUHAyBQZAMHAAAAQAcHApBgbAQGAvBwdAMHAuAwcAQHAvBgcAEGAnBQZA4CAkBAbAwGAsAQLAIDAxAwNAcDA5AAAAgBAhDQMAAAAAAQLctneQQAZhJ3aAAgOAkAAEAw7+W5WWOFMcVmfuAAAA4XXFAAAAQGAAAAAAoBYAAJAAAAAAAgCrmEAkBQYAIHArBAAAQBATCAAAcCAv7bhAAAAxMFUTdbnu+fjc8/QByIhApzoz1SaAAAAkBAAAAwHAAAAsAAAAcHApBgbAQGAvBwdAMHAuAQaA0GAtBQZAIHAzBQaAYHAlBwYA8GAuBAdAIHAvBAbAAHAhBgbAUGAsBwXAMGA3BQNA4GAxAAaAIDA0BAeAkHAlBwdAkHAAAAAAAAAAAAAAQBAAAA

Interval=1800000
Shuffle=1
[Control Panel\Colors]
Scrollbar=200 200 200
Background=81 92 107
ActiveTitle=153 180 209
InactiveTitle=191 205 219
Menu=240 240 240
Window=255 255 255
WindowFrame=100 100 100
MenuText=0 0 0
WindowText=0 0 0
TitleText=0 0 0
ActiveBorder=180 180 180
InactiveBorder=244 247 252
AppWorkspace=171 171 171
Hilight=0 120 215
HilightText=255 255 255
ButtonFace=240 240 240
ButtonShadow=160 160 160
GrayText=109 109 109
ButtonText=0 0 0
InactiveTitleText=0 0 0
ButtonHilight=255 255 255
ButtonDkShadow=105 105 105
ButtonLight=227 227 227
InfoText=0 0 0
InfoWindow=255 255 225
ButtonAlternateFace=0 0 0
HotTrackingColor=0 102 204
GradientActiveTitle=185 209 234
GradientInactiveTitle=215 228 242
MenuHilight=0 120 215
MenuBar=240 240 240
